source 'https://rubygems.org'

gem 'rails',                '4.1.6'

gem 'bootstrap-generators', '~> 3.2.0'
gem 'bootstrap-sass'
gem 'cancan'
gem 'coffee-rails',         '~> 4.0.0'
gem 'devise'
gem 'devise-i18n-views'
gem 'friendly_id'
gem 'heroku_secrets',       github: 'alexpeattie/heroku_secrets'
gem 'high_voltage'
gem 'jquery-rails'
gem 'mysql2'
gem 'pg'
gem 'pickadate-rails'
gem 'sass-rails',           '~> 4.0.3'
gem 'simple_form'
gem 'slim'
gem 'slim-rails'
gem 'spring',               group: :development
gem 'therubyracer',         platforms: :ruby
gem 'turbolinks'
gem 'uglifier',             '>= 1.3.0'
gem 'unicorn'
